services:
  generator:
    build:
      context: .
      dockerfile: Dockerfile.generator
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network
  validator:
    build:
      context: .
      dockerfile: Dockerfile.validator
    ports:
      - "5001:5001"
    networks:
      - app-network
  iteration-agent:
    build:
      context: .
      dockerfile: Dockerfile.iteration-agent
    depends_on:
      - generator
      - validator
    networks:
      - app-network
networks:
  app-network:
    driver: bridge